// Package e2e holds end-to-end tests that exercise the real worker HTTP
// handler, the master client, the archive/replace placement, and subtitle
// extraction against a synthetic MKV generated by ffmpeg.
//
// The tests skip if ffmpeg/ffprobe are unavailable on the host.
package e2e

import (
	"context"
	"encoding/json"
	"errors"
	"io"
	"log/slog"
	"net/http"
	"net/http/httptest"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/3n3a/mediforge/internal/archive"
	"github.com/3n3a/mediforge/internal/client"
	"github.com/3n3a/mediforge/internal/encode"
	"github.com/3n3a/mediforge/internal/httpapi"
	"github.com/3n3a/mediforge/internal/probe"
	"github.com/3n3a/mediforge/internal/subtitles"
)

const (
	testToken   = "e2e-secret-token"
	ffmpegBin   = "ffmpeg"
	ffprobeBin  = "ffprobe"
	testEncoder = "libx264" // force CPU path so the test is deterministic across hosts
)

// requireFFmpeg skips the test when ffmpeg/ffprobe aren't on PATH.
func requireFFmpeg(t *testing.T) {
	t.Helper()
	for _, bin := range []string{ffmpegBin, ffprobeBin} {
		if _, err := exec.LookPath(bin); err != nil {
			t.Skipf("%s not found on PATH: %v", bin, err)
		}
	}
}

// makeTestMKV generates a ~1-second MKV with:
//   - mpeg4 video (not our target, so encoding is required)
//   - ac3 audio  (ditto)
//   - optional embedded SRT subtitle track when withSub is true
func makeTestMKV(t *testing.T, out string, withSub bool) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}

	args := []string{
		"-y", "-hide_banner", "-nostats",
		"-f", "lavfi", "-i", "testsrc2=duration=2:size=160x120:rate=10",
		"-f", "lavfi", "-i", "sine=frequency=1000:duration=2:sample_rate=48000",
	}
	maps := []string{"-map", "0:v", "-map", "1:a"}
	if withSub {
		sub := filepath.Join(filepath.Dir(out), "_source.srt")
		const srtBody = "1\n00:00:00,100 --> 00:00:00,800\ne2e test subtitle\n\n"
		if err := os.WriteFile(sub, []byte(srtBody), 0o644); err != nil {
			t.Fatalf("write srt: %v", err)
		}
		args = append(args, "-f", "srt", "-i", sub)
		maps = append(maps, "-map", "2:s")
	}
	args = append(args, maps...)
	args = append(args, "-c:v", "mpeg4", "-c:a", "ac3")
	if withSub {
		args = append(args, "-c:s", "srt")
	}
	args = append(args, "-t", "2", out)

	cmd := exec.Command(ffmpegBin, args...)
	outBuf, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("ffmpeg generate mkv: %v\n%s", err, outBuf)
	}
}

// newWorkerServer spins up an httptest.Server that behaves like the real
// cmd/mediforge-worker binary: bearer-auth on POST /encode, single-flight
// mutex, runs encode.Encode, streams the MP4 back.
func newWorkerServer(t *testing.T) *httptest.Server {
	t.Helper()
	workDir := t.TempDir()
	var mu sync.Mutex

	mux := http.NewServeMux()
	mux.HandleFunc("GET /health", func(w http.ResponseWriter, r *http.Request) {
		_ = json.NewEncoder(w).Encode(httpapi.HealthResponse{OK: true})
	})
	mux.Handle("POST /encode", httpapi.BearerAuth(testToken, http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if !mu.TryLock() {
			w.Header().Set("Retry-After", "1")
			writeJSONErr(w, http.StatusServiceUnavailable, "worker_busy", "busy", "")
			return
		}
		defer mu.Unlock()

		filename := r.Header.Get(httpapi.HeaderFilename)
		if filename == "" {
			filename = "input.bin"
		}
		filename = filepath.Base(filename)
		ext := filepath.Ext(filename)
		if ext == "" {
			ext = ".bin"
		}
		inPath := filepath.Join(workDir, "in"+ext)
		outPath := filepath.Join(workDir, "out.mp4")
		defer os.Remove(inPath)
		defer os.Remove(outPath)

		in, err := os.Create(inPath)
		if err != nil {
			writeJSONErr(w, http.StatusInternalServerError, "io_error", "create input", err.Error())
			return
		}
		if _, err := io.Copy(in, r.Body); err != nil {
			_ = in.Close()
			writeJSONErr(w, http.StatusBadRequest, "upload_failed", "read body", err.Error())
			return
		}
		_ = in.Close()

		res, err := encode.Encode(r.Context(), encode.Options{
			FFmpegBin: ffmpegBin,
			Encoder:   testEncoder,
			Input:     inPath,
			Output:    outPath,
		})
		if err != nil {
			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusInternalServerError)
			_ = json.NewEncoder(w).Encode(httpapi.ErrorResponse{
				Error: err.Error(), Code: "ffmpeg_failed", StderrTail: res.StderrTail,
			})
			return
		}
		st, err := os.Stat(outPath)
		if err != nil {
			writeJSONErr(w, http.StatusInternalServerError, "io_error", "stat output", err.Error())
			return
		}
		out, err := os.Open(outPath)
		if err != nil {
			writeJSONErr(w, http.StatusInternalServerError, "io_error", "open output", err.Error())
			return
		}
		defer out.Close()
		w.Header().Set("Content-Type", httpapi.ContentTypeMP4)
		w.Header().Set("Content-Length", strconv.FormatInt(st.Size(), 10))
		w.WriteHeader(http.StatusOK)
		_, _ = io.Copy(w, out)
	})))

	srv := httptest.NewServer(mux)
	t.Cleanup(srv.Close)
	return srv
}

func writeJSONErr(w http.ResponseWriter, status int, code, msg, detail string) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(httpapi.ErrorResponse{Error: msg, Code: code, Detail: detail})
}

// dispatchOne runs the non-cache parts of the master pipeline for a single
// file: probe → encode via client → extract subs → SafeReplace or SafeArchive.
// The cache/jobs-ledger plumbing isn't exercised here; it's covered by
// package-level tests elsewhere.
func dispatchOne(t *testing.T, ctx context.Context, workerURL, src, archiveTarget string) string {
	t.Helper()
	cli := client.New(workerURL, testToken, 2*time.Minute, 5*time.Minute)

	// sanity: source is not already in target format
	pres, err := probe.Run(ctx, ffprobeBin, src)
	if err != nil {
		t.Fatalf("probe src: %v", err)
	}
	if pres.IsTarget {
		t.Fatalf("expected non-target source, got IsTarget=true (%s)", pres.Reason)
	}

	tmp := archive.TmpPathFor(src)
	t.Cleanup(func() { _ = os.Remove(tmp) })

	if _, err := cli.Encode(ctx, src, tmp); err != nil {
		t.Fatalf("client.Encode: %v", err)
	}
	if st, err := os.Stat(tmp); err != nil || st.Size() == 0 {
		t.Fatalf("encoded tmp missing or empty: stat=%v err=%v", st, err)
	}

	sctx, scancel := context.WithTimeout(ctx, 30*time.Second)
	defer scancel()
	sidecars, err := subtitles.Extract(sctx, discardLogger(), ffmpegBin, ffprobeBin, src)
	if err != nil {
		t.Fatalf("subtitles.Extract: %v", err)
	}

	var final string
	if archiveTarget != "" {
		final, err = archive.SafeArchiveWithSidecars(src, tmp, archiveTarget, sidecars)
	} else {
		final, err = archive.SafeReplaceWithSidecars(src, tmp, sidecars)
	}
	if err != nil {
		t.Fatalf("placement: %v", err)
	}

	// Verify the encoded file is in target format.
	fres, err := probe.Run(ctx, ffprobeBin, final)
	if err != nil {
		t.Fatalf("probe final: %v", err)
	}
	if !fres.IsTarget {
		t.Fatalf("encoded output is not target format: reason=%s, codec=%s profile=%s audio=%s",
			fres.Reason, fres.VideoCodec, fres.VideoProfile, fres.AudioCodec)
	}
	return final
}

// ---------------- Tests ----------------

func TestE2E_ReplaceMode(t *testing.T) {
	requireFFmpeg(t)
	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Minute)
	defer cancel()

	srv := newWorkerServer(t)

	libRoot := t.TempDir()
	src := filepath.Join(libRoot, "Season 01", "test.mkv")
	makeTestMKV(t, src, true /*withSub*/)

	final := dispatchOne(t, ctx, srv.URL, src, "")

	wantFinal := filepath.Join(libRoot, "Season 01", "test.mp4")
	if final != wantFinal {
		t.Fatalf("final = %s, want %s", final, wantFinal)
	}
	mustExist(t, wantFinal)
	mustExist(t, filepath.Join(libRoot, "Season 01", "test.default.srt"))
	mustNotExist(t, src) // original deleted in replace mode

	// SRT sidecar is non-trivial in content.
	sub, err := os.ReadFile(filepath.Join(libRoot, "Season 01", "test.default.srt"))
	if err != nil || !strings.Contains(string(sub), "e2e test subtitle") {
		t.Fatalf("subtitle extraction missing expected text: err=%v body=%q", err, sub)
	}
}

func TestE2E_ArchiveMode(t *testing.T) {
	requireFFmpeg(t)
	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Minute)
	defer cancel()

	srv := newWorkerServer(t)

	libRoot := t.TempDir()
	archRoot := t.TempDir()
	rel := filepath.Join("Season 01", "test.mkv")
	src := filepath.Join(libRoot, rel)
	makeTestMKV(t, src, true)

	archiveTarget := filepath.Join(archRoot, "tv", rel)
	final := dispatchOne(t, ctx, srv.URL, src, archiveTarget)

	wantFinal := filepath.Join(libRoot, "Season 01", "test.mp4")
	if final != wantFinal {
		t.Fatalf("final = %s, want %s", final, wantFinal)
	}
	mustExist(t, wantFinal)
	mustExist(t, filepath.Join(libRoot, "Season 01", "test.default.srt"))
	mustNotExist(t, src) // moved to archive

	// Archived original preserved exactly where we asked.
	archived, err := os.Stat(archiveTarget)
	if err != nil {
		t.Fatalf("archive target missing: %v", err)
	}
	if archived.Size() == 0 {
		t.Fatalf("archive target empty")
	}
}

func TestE2E_ArchiveMode_CollisionIdenticalDeletesSource(t *testing.T) {
	requireFFmpeg(t)
	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Minute)
	defer cancel()

	srv := newWorkerServer(t)

	libRoot := t.TempDir()
	archRoot := t.TempDir()
	rel := filepath.Join("Season 01", "test.mkv")
	src := filepath.Join(libRoot, rel)
	archiveTarget := filepath.Join(archRoot, "tv", rel)

	// Make the src, then pre-copy it to the archive with matching mtime so
	// the collision path takes "identical, skip move" branch.
	makeTestMKV(t, src, false)
	if err := os.MkdirAll(filepath.Dir(archiveTarget), 0o755); err != nil {
		t.Fatal(err)
	}
	copyFile(t, src, archiveTarget)
	st, err := os.Stat(src)
	if err != nil {
		t.Fatal(err)
	}
	if err := os.Chtimes(archiveTarget, st.ModTime(), st.ModTime()); err != nil {
		t.Fatal(err)
	}
	archivedStatBefore, _ := os.Stat(archiveTarget)

	dispatchOne(t, ctx, srv.URL, src, archiveTarget)

	mustNotExist(t, src)
	archivedStatAfter, err := os.Stat(archiveTarget)
	if err != nil {
		t.Fatalf("archive target missing after identical-collision: %v", err)
	}
	if archivedStatAfter.Size() != archivedStatBefore.Size() || archivedStatAfter.ModTime().Unix() != archivedStatBefore.ModTime().Unix() {
		t.Fatal("archive target changed despite identical-collision (should be untouched)")
	}
	// No .1 suffix should exist.
	mustNotExist(t, filepath.Join(archRoot, "tv", "Season 01", "test.1.mkv"))
}

func TestE2E_ArchiveMode_CollisionDifferentAutoSuffix(t *testing.T) {
	requireFFmpeg(t)
	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Minute)
	defer cancel()

	srv := newWorkerServer(t)

	libRoot := t.TempDir()
	archRoot := t.TempDir()
	rel := filepath.Join("Season 01", "test.mkv")
	src := filepath.Join(libRoot, rel)
	archiveTarget := filepath.Join(archRoot, "tv", rel)

	// Pre-place a *different* file at archiveTarget so the collision takes
	// the auto-suffix branch. Use stale mtime to guarantee mismatch.
	if err := os.MkdirAll(filepath.Dir(archiveTarget), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(archiveTarget, []byte("unrelated-old-content"), 0o644); err != nil {
		t.Fatal(err)
	}
	_ = os.Chtimes(archiveTarget, time.Unix(1, 0), time.Unix(1, 0))

	makeTestMKV(t, src, false)

	dispatchOne(t, ctx, srv.URL, src, archiveTarget)

	// Original pre-existing archive untouched.
	if got, _ := os.ReadFile(archiveTarget); string(got) != "unrelated-old-content" {
		t.Fatalf("pre-existing archive altered: %q", got)
	}
	// Source landed at suffix .1
	suffixed := filepath.Join(archRoot, "tv", "Season 01", "test.1.mkv")
	if st, err := os.Stat(suffixed); err != nil || st.Size() == 0 {
		t.Fatalf("suffixed archive missing: err=%v", err)
	}
	mustNotExist(t, src)
}

func TestE2E_HealthCheck(t *testing.T) {
	srv := newWorkerServer(t)
	resp, err := http.Get(srv.URL + "/health")
	if err != nil {
		t.Fatalf("health GET: %v", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != 200 {
		t.Fatalf("status %d", resp.StatusCode)
	}
	var h httpapi.HealthResponse
	if err := json.NewDecoder(resp.Body).Decode(&h); err != nil {
		t.Fatalf("decode: %v", err)
	}
	if !h.OK {
		t.Fatal("health.OK = false")
	}
}

func TestE2E_EncodeRejectsUnauthenticated(t *testing.T) {
	srv := newWorkerServer(t)
	resp, err := http.Post(srv.URL+"/encode", "application/octet-stream", strings.NewReader("nothing"))
	if err != nil {
		t.Fatalf("POST: %v", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusUnauthorized {
		t.Fatalf("status = %d, want 401", resp.StatusCode)
	}
}

// ---------------- helpers ----------------

func mustExist(t *testing.T, path string) {
	t.Helper()
	if _, err := os.Stat(path); err != nil {
		t.Fatalf("expected %s to exist: %v", path, err)
	}
}

func mustNotExist(t *testing.T, path string) {
	t.Helper()
	if _, err := os.Stat(path); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("expected %s to not exist, got err=%v", path, err)
	}
}

func copyFile(t *testing.T, src, dst string) {
	t.Helper()
	in, err := os.Open(src)
	if err != nil {
		t.Fatal(err)
	}
	defer in.Close()
	out, err := os.Create(dst)
	if err != nil {
		t.Fatal(err)
	}
	defer out.Close()
	if _, err := io.Copy(out, in); err != nil {
		t.Fatal(err)
	}
}

// discardLogger returns a *slog.Logger that drops everything, keeping test
// output quiet.
func discardLogger() *slog.Logger {
	return slog.New(slog.NewTextHandler(io.Discard, &slog.HandlerOptions{Level: slog.LevelError + 1}))
}
